apiVersion: v1
kind: Service
metadata:
  name: mobile-info-ui
spec:
  type: NodePort
  selector:
    app: MyApp
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8090
      targetPort: 8090
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-info-ui
spec:
  selector:
    matchLabels:
      app: mobile-info-ui
  replicas: 3
  template:
    metadata:
      labels:
        app: mobile-info-ui
    spec:
      containers:
        - name: mobile-info-ui
          image: hashanr/mobile-info-ui:1.1.0-SNAPSHOT
          ports:
            - containerPort: 8090